### ISSUE TITLE
client_secret must be provided in the Authorization header

### ISSUE THREAD

**Issue by M2xAy** [krakend/krakend-ce#527]
Hi Krakendio Team
I activated on endpoint the auth and receive the following error

any idea or suggestion? 
Best Regards

KrakendD runs on Debian with executabel(no Docker)

`client_secret must be provided in the Authorization header`

           "extra_config": {
                    "auth/client-credentials": {
                        
                        "client_id": "myapp-id",
                        "client_secret": "my-app-secret",
                        "token_url": "http://ubuntu2004:9000/token",
                        "scopes": "openid, email",
                        "endpoint_params": {
                        }
                    }
                }

**Comment by kpacha** [comment]
hi @M2xAy , the oauth2 client-credentials mw is designed to be defined at the backend since it's intended to identify krakend as the gateway sending the request to your backend and not intended to identify your clients

more info at the documentation: https://www.krakend.io/docs/authorization/client-credentials/

cheers!
