### ISSUE TITLE
Proposal add an actively maintained HTTP cache middleware

### ISSUE THREAD

**Issue by darkweak** [krakend/krakend-ce#714]
**Version of KrakenD you are using**
`*`

**Is your feature request related to a problem? Please describe.**
There are already 2 existing repositories.  
* `https://github.com/krakendio/krakend-httpcache` defines an HTTP cache client
* `https://github.com/krakendio/httpcache` only supports private cache (as described in the documentation) and doesn't provide any API to `PURGE` the data, to use some keys group like the `Surrogate-Keys`.

**Describe the solution you'd like**
I can provide an actively maintained, RFC compliant middleware. It's already used by the `cache-handler` from caddy, can be used through Træfik, Tyk and other reverse-proxies/APIM. It supports the new RFCs: 
 - Cache-Status HTTP response header
 - targeted cache-control

It also supports the surrogate keys and CDN invalidation.
This project is called [Souin](https://github.com/darkweak/souin)

**Describe alternatives you've considered**
I didn't considered to rewrite any of existing repositories because the first one is not maintained and the second one is an HTTP client.

Let me know about that, what's your opinion about that. If it's worth to develop that. ✌️

**Comment by alombarte** [comment]
Hi @darkweak ,

Thank you for offering to build and maintain this middleware; it is indeed an interesting issue.

I have mixed feelings about it. We support **micro**caching on endpoints that do not change frequently and whose responses do not frequently vary so that we can alleviate the pressure on the backend. Currently, our users that need to apply this kind of cache place a Varnish or similar product in front of KrakenD.

This addition would open the door to full caching, which is awesome for the user as functionality but not so good for the product's architecture if we don't do it properly. We will need to see what the approach is. Everyone assumes a `PURGE` does its work, but this will have a severe impact (at least what I imagine) on a **distributed and uncoordinated** system like KrakenD, and so far, we haven't found a convincing approach to this problem.

I am interested in your thoughts and in continuing this conversation.

**Comment by darkweak** [comment]
Hey @alombarte thank you for your fast answer. I understand your concerns about that and that's legitimate. I'll try to explain more my minds.

As you explain,
> Currently, our users that need to apply this kind of cache place a Varnish or similar product in front of KrakenD.

Users have to setup, manage and maintain their own Varnish instance on their own servers or pay the VarnishEE.  
The Varnish community doesn't support the distributed or filesystem caching storage natively and is only available in the EE.
With the Souin approach, they just have to run a KrakenD instance, load the pre-built plugin in KrakenD and just fill the configuration in the KrakenD configuration itself. No more VCL knowledges are required to setup and manage their HTTP cache. And as souin supports natively distributed, filesystem or in-memory storage it will work perfectly with the **distributed** side of KrakenD.

> This addition would open the door to full caching, which is awesome for the user as functionality but not so good for the product's architecture if we don't do it properly.

I totally agree with you that's why we have to discuss about the pros and cons. To be honest I don't understand why it would not be good for product's architecture.

**Comment by alombarte** [comment]
Hi @darkweak,

Whether this is incorporated by default on KrakenD packaging or available as an extra component or plugin, it is interesting to continue the conversation. If you have a proposal to submit, we will carefully review it and iterate it.

Thanks for your contribution!
