### ISSUE TITLE
I don't understand the meaning of the panels on Grafana.

### ISSUE THREAD

**Issue by zaco-chen** [krakend/krakend-ce#753]
Environment info:

KrakenD version: 2.2.0
System info: CentOS Linux 7.9

 Additional environment information:
for-influxdb-v1.json

Describe what are you trying to do:
I have concerns about the panels on Grafana and would like to seek advice.

### 1. The number of "Proxy Requests" and "Backend Requests" is higher than that of "Router Requests", and the number of "Proxy Requests" is equal to the number of "Backend Requests".
  "Router Requests"：13.8K
  "Proxy Requests"：371K
  "Backend Requests"：371K
![image](https://github.com/krakendio/krakend-ce/assets/83002368/334ccb07-f09b-44be-9ca9-40e2253e8d0b)

### 2. When I sum up the response times of the router, proxy, and backend for the endpoints with the longest response times, why is the value different from the panel showing the "Max Response Time"?
  **Max Response Time：1.82s**
![image](https://github.com/krakendio/krakend-ce/assets/83002368/e87b1bac-d488-467e-93b3-0302d31b798a)

      
      **Router** (Endpoint Response Time (ms))
       Metric      Avg       Min       **Max**     Current
      /api/a     441.59   400.96   **474.63**    474.63
![image](https://github.com/krakendio/krakend-ce/assets/83002368/9c9f1f8b-7a49-42c1-8cf1-e5435fc63114)

      **Proxy** (Pipe Response Time (ms))
       Metric      Avg       Min       **Max**     Current
      /api/a     441.47   400.83    **474.52**    474.52
![image](https://github.com/krakendio/krakend-ce/assets/83002368/83b8e7e4-a7df-4d48-96a6-f5bb4513e01f)

      **Backend** (Backend Response Time (ms))
       Metric      Avg       Min       **Max**     Current
      /api/a     441.47   400.83    **474.51**    474.51
![image](https://github.com/krakendio/krakend-ce/assets/83002368/3603285a-b0e4-4e6f-9d3c-420b996d008e)

      474.63+474.52+474.51 ≠ 1.82s

**Comment by alombarte** [comment]
- The router requests are the connections between users and KrakenD
- The backend requests are the number of connections KrakenD made to your backends.
- The proxy requests are the total requests in the proxy pipe (the aggregation context)

This backend requests counter is usually higher because of aggregation. Just to remind you, one endpoint the user consumes could originate many connections out to your backend services. Either because you have multiple backends in your endpoints, concurrent_calls, etc...

The maximum response time is not the sum of the layers; it is the slowest connection ever seen.
