### ISSUE TITLE
Json ouput response encoding 

### ISSUE THREAD

**Issue by P-VINODKRISHNA** [krakend/krakend-ce#946]
In my krakend json when I make assign output encoding as json only successfull requests response is getting shown to frontend but failed ones coming invalid status code in krakend logs can anybody give me clarity on this if I choose no-op I am facing cors issue in frontend

**Comment by thedae** [comment]
When you configure an endpoint with multiple backends, KrakenD is designed to discard failed requests if at least one of them responded correctly. In this scenario, the `X-Krakend-Completed` header flag will be set to `false` to let the client know there's something wrong. More info about the merge aggregation strategy here: https://www.krakend.io/docs/endpoints/response-manipulation/#aggregation-and-merging

You can ignore this strategy and go for a `no-op` configuration as you mentioned. If you are facing CORS issues is most likely because the `input_headers` config parameter is set to wildcard `*`, thus all the headers from the frontend request, including the CORS ones, are proxied to the backends. To workaround this, you can either:
* Disable the CORS from the frontend
* Tell krakend to remove the CORS headers before making the requests to the backends, check this thread for more info: https://github.com/krakend/krakend-cors/issues/18#issuecomment-970047860
